
# Inserts a blank line between shell prompts
add_newline = true

[aws]
symbol = "îŒ½  "

[directory]
truncation_length = 4
#truncation_symbol = "â€¦/"
home_symbol = "ïŸ ~"
read_only_style = "197"
read_only = " ï€£ "

[docker_context]
symbol = "ïŒˆ "
only_with_files = true

[git_branch]
symbol = "ï˜ "

[nodejs]
symbol = "îœ˜ "

[package]
symbol = "ï£– "

[perl]
symbol = "ğŸª "

[python]
symbol = "ï Ÿ "

[git_status]
format = '[\($all_status$ahead_behind\)]($style) '
style = "bold green"
conflicted = "ğŸ³"
up_to_date = "ï† "
untracked = "ï”© ${count}"
ahead = "â‡¡${count}"
diverged = "â‡•â‡¡${ahead_count}â‡£${behind_count}"
behind = "â‡£${count}"
stashed = "ï£– "
modified = "ï„ ${count}"
staged = '[++\($count\)](green)'
renamed = "ïª¶${count} "
deleted = "ï€” ${count} "
